--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IgPlugin/GaySexLegends
build-by-default: true
branches:
- main
projects:
  GaySexLegends:
    path: ""
    libs:
      - src: NhanAZ/libRegRsp/libRegRsp
        version: 1.0.3

...
